name: Nikto Scan

on:
  push:
    branches:
      - main

jobs:
  nikto-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Run Nikto Scan
      run: |
        docker run sullo/nikto -h http://www.rbxgold.com


